### ISSUE TITLE
Enable & disable command

### ISSUE THREAD

**Issue by mooziii** [bluefireoly/pacmc#10]
A command which disabled or enables mods

**Comment by bluefireoly** [comment]
Can you give an example when you would need this feature? Maybe it can be done in a better way.

**Comment by bluefireoly** [comment]
bump?

**Comment by mooziii** [comment]
As an example, if you have a 1.16 mod installed and want to start minecraft 1.17 then you can simply deactivate the 1.16 mod

**Comment by bluefireoly** [comment]
You can use the `pacmc archive load` command to manage multiple "profiles" for the different minecraft versions. Alternatively, you can use `pacmc archive version 1.16` to switch the version of an archive (.minecraft by default) without having to remove any mods.

**Comment by mooziii** [comment]
oh okay
