### ISSUE TITLE
PowerShell could not display u2500 and u2192

### ISSUE THREAD

**Issue by WordlessEcho** [bluefireoly/pacmc#12]
![image](https://user-images.githubusercontent.com/12007025/125641557-d9664c18-62e4-48be-8734-5909985f30dc.png)
Looks good in `cmd.exe`:
![image](https://user-images.githubusercontent.com/12007025/125641652-570ec8de-87be-4f27-a4ae-64382258b58b.png)

**Comment by WordlessEcho** [comment]
🤔
![image](https://user-images.githubusercontent.com/12007025/125642379-79640d93-5b00-4f23-8de1-cd966737bb57.png)

**Comment by bluefireoly** [comment]
The download progress symbols look right for me even when using PowerShell:
![grafik](https://user-images.githubusercontent.com/52456572/125645532-d1f7af5a-5470-43b7-af74-24b56ca4884a.png)

**Comment by bluefireoly** [comment]
The arrow on the list command is not displayed correctly, but that is a Windows Terminal issue, sadly I can't do anything about 🤷‍♂️ 

![grafik](https://user-images.githubusercontent.com/52456572/125645751-79c9a01f-63ef-4579-a6d1-ae063436df26.png)

**Comment by WordlessEcho** [comment]
I don't know why I cannot display these symbol. (
Font: Droid Sans Slashed for Powerline, Consolas

![image](https://user-images.githubusercontent.com/12007025/125649440-0b079018-fd6f-4e2d-aa13-bdb182f8cf1e.png)

**Comment by bluefireoly** [comment]
Your prompt seems to have problems some problems with special characters too

**Comment by WordlessEcho** [comment]
It is oh-my-posh. Disable it will helps to solve this problem.
![image](https://user-images.githubusercontent.com/12007025/125666222-26c33747-c94a-4a60-9bac-375242b859f5.png)

**Comment by bluefireoly** [comment]
Do you know whether I was right with my assumption that Windows Terminal is the reason for the arrow symbol (used by the `pacmc list`) command to not be displayed correctly?

Because in your last screenshot the arrow is there, but it isn't PowerShell running in the Windows Terminal either.

**Comment by WordlessEcho** [comment]
> Do you know whether I was right with my assumption that Windows Terminal is the reason for the arrow symbol (used by the `pacmc list`) command to not be displayed correctly?
> 
> Because in your last screenshot the arrow is there, but it isn't PowerShell running in the Windows Terminal either.

It is an third-party powershell plugin called “oh-my-posh” causing this problem.

**Comment by bluefireoly** [comment]
Yes but even without oh-my-posh it is still buggy in the new Windows Terminal, right?

**Comment by WordlessEcho** [comment]
> Yes but even without oh-my-posh it is still buggy in the new Windows Terminal, right?

No.

**Comment by WordlessEcho** [comment]
I test and find out that using the theme by oh-my-gosh will cause this problem. I am using agnoster theme currently.

**Comment by bluefireoly** [comment]
Yes but it does not have anything to do with oh-my-posh or its themes I guess, it really seems to be a Windows Terminal problem.

I also had this problem without any PowerShell extension:
https://github.com/bluefireoly/pacmc/issues/12#issuecomment-879972915

**Comment by WordlessEcho** [comment]
> Yes but it does not have anything to do with oh-my-posh or its themes I guess, it really seems to be a Windows Terminal problem.
> 
> I also had this problem without any PowerShell extension:
> [#12 (comment)](https://github.com/bluefireoly/pacmc/issues/12#issuecomment-879972915)
> (the question mark should be an arrow)

It works fine on my PowerShell.
![image](https://user-images.githubusercontent.com/12007025/128590238-6a190af5-0208-4b29-9ebc-6f348408153a.png)

**Comment by jakobkmar** [comment]
If you update pacmc now, it uses a different arrow on Windows, because I just have no way to tell where it works and where it doesn't.
It is a workaround, but it improves the overall compatibility.
