### ISSUE TITLE
Build: Unable to delete directory 'packages'

### ISSUE THREAD

**Issue by WordlessEcho** [bluefireoly/pacmc#9]
I am trying to build this project on IntelliJ IDEA 2021.1.3 on Windows 11.

```
Unable to delete directory 'D:\files\src\pacmc\packages'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - D:\files\src\pacmc\packages\aur\pacmc\.SRCINFO
  - D:\files\src\pacmc\packages\aur\pacmc
  - D:\files\src\pacmc\packages\aur
```

**Comment by bluefireoly** [comment]
Weird, maybe it does have something to do that you did just clone the repository into `D:\files\` and another process is active there?

**Comment by WordlessEcho** [comment]
> Weird, maybe it does have something to do with that you did just clone the repository into `D:\files\` and another process is active there?

I delete [this line of code in build.gradle.kts](https://github.com/bluefireoly/pacmc/blob/d22f5c554410ae049faa9b0e6acb31f49afe9001/build.gradle.kts#L95). Works fine for me.

```
workingDir("packages/aur/pacmc/")
```

**Comment by bluefireoly** [comment]
The `packages` directory inside the root directory of the project contains some git submodules which you do not have access to, but I do not see why Gradle would try to "delete" the directory.

**Comment by bluefireoly** [comment]
Temporary fix with faf592b
but I don't know how it will behave if someone on arch who does not have permission is trying to build the project

**Comment by WordlessEcho** [comment]
Tested and works great for me. 👍

**Comment by bluefireoly** [comment]
Now using the Gradle task avoidance API, meaning that it should be fixed in a non-temporary way.
